Discord:
  token: $token
  commande:
    start: "!"
    cmd:
      - "pong"
      - "ask"
      - "help"
      - "start"
  response:
    help:
      - "!pong."
      - "!ask: affiche depuis combien de temps le pc n'est pas en activité."
      - "!help: affiche les commandes."
      - "!start: démarre le PC."
    startup: "Démarage de l'ordinateur!"

    ask:
      available: "l'ordinateur est en inactivité depuis: "
      unvailable: "L'ordinateur est actuelement non disponnible!"
      switched_off: "L'ordinateur est actuelement éteint"
      timeMin: $timeMinAFK
      commande: "time"

    pong: "Ping!"

Startup:
  wol:
    mac: $mac

Server:
  port: $port
  ip: $address
