version: "3"
services:
  discordbot:
    image: tecnelm/discordbot:latest
    container_name: botDiscord
    environment:
      - TOKEN=<token of discordBot>
      - PORT=<port to lister>
      - ADDRESS=<address on wich interface to listen '' for all>
      - MAC=<Mac address of the computer to WOL>
      - TIME_MIN_AFK= <time to accept afk>
    network_mode: host
    restart: unless-stopped
